### ISSUE TITLE
invalid syntax?

### ISSUE THREAD

**Issue by Randomfinger** [cemsbr/wikipedia2json#1]
Hi, 

I tried to run the script but first it could not find w2j.py.
I cp it to the scripts folder.
Then I executed: bzcat asdfWikidump.xml.bz2 > output.xml
-->works.

Then I tried: 
user@pc:~/wikipedia2json/scripts$ python w2j.py output.xml

--> fails:
Traceback (most recent call last):
  File "w2j.py", line 2, in <module>
    from wiki2json import Wiki2Json
  File "/home/zoe/wikipedia2json/scripts/wiki2json.py", line 10
    def print(_args, *_kwargs):
            ^
SyntaxError: invalid syntax

**Comment by cemsbr** [comment]
Try to set your PYTHONPATH like this:

``` bash
user@pc:~/wikipedia2json/scripts$ PYTHONPATH=.. bzcat asdfWikidump.xml.bz2 | ./w2j.py >output.json
```

**Comment by cemsbr** [comment]
Reading it again, it seems that the problem might be related to the python version. If you don't run `./w2j.py`, be sure to use python 3 like this: `python3 w2j.py`.
